# Generated by Django 5.2.7 on 2025-11-16 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='Password_Hash', max_length=128)),
                ('firstname', models.CharField(db_column='Firstname', max_length=100)),
                ('lastname', models.CharField(db_column='Lastname', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.AutoField(db_column='Neighborhood_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'Neighborhood',
            },
        ),
        migrations.CreateModel(
            name='Pricebucket',
            fields=[
                ('pricebucket_id', models.AutoField(db_column='Pricebucket_ID', primary_key=True, serialize=False)),
                ('range', models.CharField(db_column='Range', max_length=100)),
            ],
            options={
                'db_table': 'Pricebucket',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type_id', models.AutoField(db_column='Property_Type_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
                'db_table': 'Property_Type',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(db_column='Status_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(db_column='Listing_ID', primary_key=True, serialize=False)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('is_visible', models.BooleanField(db_column='Is_Visible', default=True)),
                ('is_featured', models.BooleanField(db_column='Is_Featured', default=False)),
                ('bedrooms', models.IntegerField(blank=True, db_column='Bedrooms', null=True)),
                ('bathrooms', models.DecimalField(blank=True, db_column='Bathrooms', decimal_places=1, max_digits=3, null=True)),
                ('square_footage', models.IntegerField(blank=True, db_column='Square_Footage', null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Sold', 'Sold')], db_column='Status', max_length=20, null=True)),
                ('listed_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='Created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.ForeignKey(blank=True, db_column='Neighborhood_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.neighborhood')),
                ('pricebucket', models.ForeignKey(blank=True, db_column='Pricebucket_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.pricebucket')),
                ('property_type', models.ForeignKey(blank=True, db_column='Property_Type_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.propertytype')),
                ('status_id', models.ForeignKey(blank=True, db_column='Status_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.status')),
            ],
            options={
                'db_table': 'Listing',
                'ordering': ['-listed_date'],
            },
        ),
        migrations.CreateModel(
            name='OmahaResource',
            fields=[
                ('omaha_resource_id', models.AutoField(db_column='Omaha_Resource_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('url', models.URLField(blank=True, db_column='URL', null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True)),
                ('is_published', models.BooleanField(db_column='Is_Published', default=False)),
                ('user', models.ForeignKey(blank=True, db_column='User_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omaha_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Omaha_Resource',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(db_column='Photo_ID', primary_key=True, serialize=False)),
                ('image_data', models.BinaryField(blank=True, db_column='Image_Data', null=True)),
                ('photo_display_order', models.IntegerField(blank=True, db_column='Phot_Display_Order', null=True)),
                ('listing', models.ForeignKey(db_column='Listing_ID', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'db_table': 'Photo',
                'ordering': ['photo_display_order', 'photo_id'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('search_log_id', models.AutoField(db_column='Search_Log_ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp')),
                ('neighborhood', models.ForeignKey(blank=True, db_column='Neighborhood_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='listings.neighborhood')),
                ('pricebucket', models.ForeignKey(blank=True, db_column='Pricebucket_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='listings.pricebucket')),
                ('property_type', models.ForeignKey(blank=True, db_column='Property_Type_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='listings.propertytype')),
            ],
            options={
                'db_table': 'Search_Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
