# Generated by Django 5.2.7 on 2025-11-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_display_order',
            field=models.IntegerField(blank=True, db_column='Photo_Display_Order', null=True),
        ),
    ]
