# Generated by Django 5.2.8 on 2025-11-26 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_enforce_listing_not_null_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmahaLocation',
            fields=[
                ('omaha_location_id', models.AutoField(db_column='Omaha_Location_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('description', models.TextField(db_column='Description')),
                ('url', models.URLField(db_column='URL')),
                ('category', models.CharField(choices=[('See & Do', 'See & Do'), ('Food', 'Food'), ('Events', 'Events')], db_column='Category', max_length=50)),
                ('is_published', models.BooleanField(db_column='Is_Published', default=True)),
                ('display_order', models.IntegerField(db_column='Display_Order', default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='Created_Date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='Updated_Date')),
                ('created_by', models.ForeignKey(blank=True, db_column='Created_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omaha_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Omaha Location',
                'verbose_name_plural': 'Omaha Locations',
                'db_table': 'Omaha_Location',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
