# Generated by Django 5.2.8 on 2025-12-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_add_thumbnail_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_highlight',
            field=models.TextField(blank=True, db_column='Featured_Highlight', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='featured_title',
            field=models.CharField(blank=True, db_column='Featured_Title', max_length=120, null=True),
        ),
    ]
